# -*- coding: utf-8 -*-
"""NPositive numbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PdEGVdgSLb1SHYxx2HOUWQvjrqqTM-vI
"""

list1=[12,6,5,-1,-100,75,-34]
i=6
while i>=0:
  if list1[i]>=0:
    print(list1[i])
  i=i-1