# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NeYtYLk_yXFWu-2xAxfKqnDCltLb4a-a
"""

filename = input("Input the Filename: ")
name, extension = filename.split(".")
print("The extension of the file is:", extension)