# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NeYtYLk_yXFWu-2xAxfKqnDCltLb4a-a
"""

radius = float(input("Enter the radius of the circle: "))
area=3.14*radius*radius
print("Area of circle is ", area )