# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PdEGVdgSLb1SHYxx2HOUWQvjrqqTM-vI
"""

i= int(input('Enter limit '))
a=1
b=-1
c=0
while i>= 0:
  c=a+b
  b=a
  a=c
  print(c)
  i=i-1